name: React CI

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu 20.04

    strategy:
      matrix:
      node-version: [18.19.0]

    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build
      - run: npm test